"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter, Open_Sans, Poppins } from "next/font/google";
import { usePathname } from "next/navigation";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();
  console.log(pathName);
  const showLayout = () => {
    if (pathName.includes("/auth")) {
      return <div className="">{children}</div>;
    } else {
      return (
        <>
          <Header />
          <div className="py-5 md-max:py-10">{children}</div>
          <Footer />
        </>
      );
    }
  };
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-stamp-bg text-white`}>
        {showLayout()}
        {/* <Header />
        <div className="py-5 md-max:py-10">{children}</div>
        <Footer /> */}
      </body>
    </html>
  );
}
