"use client"

import Footer from "@/components/footer";
import "./globals.css";
// import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Image from "next/image";
import Nav from "@/components/nav";
import shellImage from "../public/icons/shell.svg";
import { usePathname } from "next/navigation";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();
  const showLayout = () => {
    if (pathName.includes("/auth")) {
      return (
        <body className={`${poppins.className} relative`}>{children}</body>
      );
    } else {
      return (
        <body className={`${poppins.className} relative pb-6`}>
          <Nav />
          {children}
          <Footer />
          <div className="absolute right-0 bottom-0 -z-50">
            <Image src={shellImage} alt="" />
          </div>
        </body>
      );
    }
  };

  return (
    <html lang="en">
      {showLayout()}
      {/* <body className={`${poppins.className} relative`}>
        <Nav />
        {children}
        <Footer />
        <div className="absolute right-0 bottom-0 -z-50">
          <Image src={shellImage} alt="" />
        </div>
      </body> */}
    </html>
  );
}
